/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Heaps;

public class MinHeap<T extends Comparable<T>> extends AbstractBinaryHeap<T> {

    public MinHeap() {
        super();
    }

    public MinHeap(T[] array) {
        super(array);
    }

    @Override
    public int compare(T o1, T o2) {
        return o1.compareTo(o2);
    }
}
