/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Heaps;

import org.junit.Test;

import Person.Person;

import static org.junit.Assert.*;

import java.lang.reflect.Array;
import java.util.Arrays;

public class HeapSortTests {
    @Test
    public void sort_LongArray_ArraySorted() {
        Heap<Long> heap = new Heap<Long>(new Long[] {9L, 10L, 7L, 8L, 5L, 6L, 3L, 4L, 1L, 2L, 0L});
        Long[] result = heap.getArray();
        Long[] expected = {0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L};
        assertArrayEquals(expected, result);
    }

    @Test
    public void sort_StringArray_ArraySorted() {
        Heap<String> heap = new Heap<String>(new String[] {"k", "j", "a", "d", "b", "f", "c", "e", "g", "h"});
        String[] result = heap.getArray();
        String[] expected = {"a", "b", "c", "d", "e", "f", "g", "h", "j", "k"};
        assertArrayEquals(expected, result);
    }

    @Test
    public void sort_PersonArray_ArraySorted() {
        Person[] array = {
            new Person("b", "2000-01-01", "7"),
            new Person("c", "2000-01-01", "3"),
            new Person("d", "2000-01-01", "9"),
            new Person("e", "2000-01-01", "5"),
            new Person("f", "2000-01-01", "6"),
            new Person("g", "2000-01-01", "2"),
            new Person("h", "2000-01-01", "8"),
            new Person("i", "2000-01-01", "4"),
            new Person("j", "2000-01-01", "1")
        };
        Heap<Person> heap = new Heap<Person>(array);
        
        Person[] expected = {
            new Person("j", "2000-01-01", "1"),
            new Person("g", "2000-01-01", "2"),
            new Person("c", "2000-01-01", "3"),
            new Person("i", "2000-01-01", "4"),
            new Person("e", "2000-01-01", "5"),
            new Person("f", "2000-01-01", "6"),
            new Person("b", "2000-01-01", "7"),
            new Person("h", "2000-01-01", "8"),
            new Person("d", "2000-01-01", "9"),
        };
        Person[] result = heap.getArray();

        assertArrayEquals(expected, result);
    }


    // @Test
    // public void insert_InsertingElementAtTheBeginning_arraySorted() {
    //     Heap<Long> heap = new Heap<Long>(new Long[] {1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L});
    //     heap.insert(0L);
    //     Long[] result = heap.getArray();
    //     result = Arrays.stream(result).filter(x -> x != null).toArray(Long[]::new);
    //     System.out.println(Arrays.toString(result));
    //     Long[] expected = {0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L};
    // }
}
